# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target '2015-07-01-ColorfulTabBarAnimation' do

pod 'TKit', '~>1.1.2'

end

target '2015-07-01-ColorfulTabBarAnimationTests' do

end

